---
title: "Beautiful chaos: the double pendulum"
output: html_notebook
---

Source: http://blog.schochastics.net/post/beautiful-chaos-the-double-pendulum/


```{r}
library(tidyverse)
library(gganimate)

# ggraph must be installed
```


```{r}
# constants
G  <-  9.807  # acceleration due to gravity, in m/s^2
L1 <-  1.0    # length of pendulum 1 (m)
L2 <-  1.0    # length of pendulum 2 (m)
M1 <-  1.0    # mass of pendulum 1 (kg)
M2 <-  1.0    # mass of pendulum 2 (kg)

parms <- c(L1,L2,M1,M2,G)

# initial conditions
th1 <-  20.0  # initial angle theta of pendulum 1 (degree)
w1  <-  0.0   # initial angular velocity of pendulum 1 (degrees per second)
th2 <-  180.0 # initial angle theta of pendulum 2 (degree)
w2  <-  0.0   # initial angular velocity of pendulum 2 (degrees per second)

state <- c(th1, w1, th2, w2)*pi/180  #convert degree to radians
```


## partial derivatives

```{r}
derivs <- function(state, t){
  L1 <- parms[1]
  L2 <- parms[2]
  M1 <- parms[3]
  M2 <- parms[4]
  G  <- parms[5]
  
  dydx    <-  rep(0,length(state))
  dydx[1] <-  state[2]
  
  del_ <-  state[3] - state[1]
  den1 <-  (M1 + M2)*L1 - M2*L1*cos(del_)*cos(del_)
  dydx[2]  <-  (M2*L1*state[2]*state[3]*sin(del_)*cos(del_) +
               M2*G*sin(state[3])*cos(del_) +
               M2*L2*state[4]*state[4]*sin(del_) -
               (M1 + M2)*G*sin(state[1]))/den1
  
  dydx[3] <-  state[4]
  
  den2 <-  (L2/L1)*den1
  dydx[4]  <-  (-M2*L2*state[4]*state[4]*sin(del_)*cos(del_) +
               (M1 + M2)*G*sin(state[1])*cos(del_) -
               (M1 + M2)*L1*state[2]*state[2]*sin(del_) -
               (M1 + M2)*G*sin(state[3]))/den2
  
  return(dydx)
}
```


## integrate

```{r}
sol <- odeintr::integrate_sys(derivs,init = state,duration = 30,
                              start = 0,step_size = 0.1)
```


## compute x, y coordinates

```{r}
x1 <-  L1*sin(sol[, 2])
y1 <-  -L1*cos(sol[, 2])
  
x2 <- L2*sin(sol[, 4]) + x1
y2 <- -L2*cos(sol[, 4]) + y1
  
df <- tibble(t=sol[,1],x1,y1,x2,y2,group=1)
```

## time steps

```{r}
ggplot(df) +
  geom_segment(aes(xend=x1, yend=y1), x=0, y=0) +
  geom_segment(aes(xend=x2, yend=y2, x=x1, y=y1)) +
  geom_point(size=5, x=0, y=0) +
  geom_point(aes(x1, y1), col="red", size=M1) +
  geom_point(aes(x2,y2), col="blue", size=M2) +
  scale_y_continuous(limits = c(-2,2)) +
  scale_x_continuous(limits = c(-2,2)) +
  ggraph::theme_graph() +
  labs(title = "{frame_time} s") +
  transition_time(t) -> p

pa <- animate(p, nframes=nrow(df), fps=20)
pa
```

## optional: add trail

```{r}
tmp <- select(df,t,x2,y2)
trail <- tibble(x = c(sapply(1:5, function(x) lag(tmp$x2, x))),
       y = c(sapply(1:5, function(x) lag(tmp$y2, x))),
       t = rep(tmp$t, 5)) %>% 
  dplyr::filter(!is.na(x))
```


```{r}
ggplot(df)+
  geom_path(data=trail,aes(x,y),colour="blue", size=0.5) +
  geom_segment(aes(xend=x1,yend=y1), x=0, y=0) +
  geom_segment(aes(xend=x2, yend=y2, x=x1, y=y1)) +
  geom_point(size=5, x=0, y=0) +
  geom_point(aes(x1, y1),col="red", size=M1) +
  geom_point(aes(x2, y2),col="blue", size=M2) +
  scale_y_continuous(limits=c(-2,2)) +
  scale_x_continuous(limits=c(-2,2)) +
  ggraph::theme_graph() +
  labs(title = "{frame_time} s") +
  transition_time(t) +
  shadow_mark(colour="grey",size=0.1,exclude_layer = 2:6) -> p

pa <- animate(p, nframes=nrow(df), fps=20)
pa
```

